# Generated by Django 4.2.1 on 2023-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tea_name", models.CharField(max_length=32, verbose_name="教师姓名")),
                (
                    "tea_sex",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="教师性别"
                    ),
                ),
                ("tea_num", models.IntegerField(verbose_name="教师电话")),
            ],
        ),
    ]
