# Generated by Django 4.2.1 on 2023-06-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cour_name", models.CharField(max_length=32, verbose_name="课程名")),
                ("cour_semester", models.IntegerField(verbose_name="学期")),
                ("cour_credit", models.IntegerField(verbose_name="学时")),
                ("cour_chour", models.IntegerField(verbose_name="学分")),
                (
                    "tea_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.teacher",
                        verbose_name="教师姓名",
                    ),
                ),
            ],
        ),
    ]
