# Generated by Django 4.2.1 on 2023-06-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scores", models.IntegerField(verbose_name="分数")),
                (
                    "cour_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.course",
                        verbose_name="课程名",
                    ),
                ),
                (
                    "std_stu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.student",
                        verbose_name="学号",
                    ),
                ),
            ],
        ),
    ]
